allocfunc(QUEST_DATA,	quest)
allocfunc(HUNT_DATA,	hdata)
allocfunc(FIGHT_DATA,	fdata)
allocfunc(LIMIT_DATA,	limit)
allocfunc(LEVEL_DATA,	level_data)
allocfunc(PETITION_DATA,petition)
allocfunc(BANK_DATA,	bank)
allocfunc(PLIST,	plist)
allocfunc(ALIST,	alist)
allocfunc(EVENT,	event)
allocfunc(TRAP_DATA,	trap)
allocfunc(struct skhash,skhash)
allocfunc(MF_DATA,	mfd)
allocfunc(HELP_AREA,	had)
allocfunc_val(MEM_DATA,		mem_data)
allocfunc_val(Entity,		entity)
