blah(AFF_BLIND,		A)
blah(AFF_INVISIBLE,	B)
blah(AFF_DETECT_EVIL,	C)

/* damage classes */
blah(DAM_NONE,		0)
blah(DAM_BASH,		1)
blah(DAM_PIERCE,	2)
blah(DAM_SLASH,		3)
blah(DAM_FIRE,		4)
blah(DAM_COLD,		5)
blah(DAM_LIGHTNING,	6)
blah(DAM_ACID,		7)
blah(DAM_POISON,	8)
blah(DAM_NEGATIVE,	9)
blah(DAM_HOLY,		10)
blah(DAM_ENERGY,	11)
blah(DAM_MENTAL,	12)
blah(DAM_DISEASE,	13)
blah(DAM_DROWNING,	14)
blah(DAM_LIGHT,		15)
blah(DAM_OTHER,		16)
blah(DAM_HARM,		17)
blah(DAM_CHARM,		18)
blah(DAM_SOUND,		19)

blah(TO_ROOM,		0)
blah(TO_NOTVICT,	1)
blah(TO_VICT,		2)
blah(TO_CHAR,		3)
blah(TO_ALL,		4)
